
flib_version=1.0.0-SNAPSHOT

mod_id=fixmyminecart
curse_id=448470
curse_slug=fix-my-minecart
mod_version=1.0.1
mod_name=fixmyminecart
mod_group_id=com.lothrazar.fixmyminecart
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
